version: "3.9"

services:
  app:
    build:
      context: "."
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: "signumpl/azchat:latest"
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__Sql=
      - ConnectionStrings__CosmosDb=
      - ConnectionStrings__BlobStorage=
      - JWT__Secret=
